version: "3.9"

services:
  haut-rn:
    build:
      context: .
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - "19000:19000"
      - "5555:5555"
    expose:
      - "19000"
    volumes:
      - .:/home/node/haut-rn
    healthcheck:
      disable: true
